---
- name: Configure application-aware Home Lab backups
  hosts: homelab_service_guests
  gather_facts: false
  become: true
  serial: 1
  any_errors_fatal: true

  roles:
    - role: homelab_backup
